- name: Pytest coverage comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
    pytest-coverage-path: ./path-to-file/pytest-coverage.txt
    pytest-xml-coverage-path: ./path-to-file/coverage.xml
    title: My Coverage Report Title
    badge-title: My Badge Coverage Title
    hide-badge: false
    hide-report: false
    create-new-comment: false
    hide-comment: false
    report-only-changed-files: false
    remove-link-from-badge: false
    junitxml-path: ./pytest-coverage.xml
    junitxml-title: My JUnit Xml Summary Title
